package Model;
// Generated 20-jul-2020 11:06:42 by Hibernate Tools 4.3.1



/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer idAlumno;
     private String nombre;
     private String apellido;
     private String ciclo;
     private String carrera;

    public Alumno() {
    }

    public Alumno(String nombre, String apellido, String ciclo, String carrera) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.ciclo = ciclo;
       this.carrera = carrera;
    }
   
    public Integer getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(Integer idAlumno) {
        this.idAlumno = idAlumno;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCiclo() {
        return this.ciclo;
    }
    
    public void setCiclo(String ciclo) {
        this.ciclo = ciclo;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }




}


