package Model;
// Generated 20-jul-2020 11:06:42 by Hibernate Tools 4.3.1



/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer idCurso;
     private String nombre;
     private int horas;

    public Curso() {
    }

    public Curso(String nombre, int horas) {
       this.nombre = nombre;
       this.horas = horas;
    }
   
    public Integer getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getHoras() {
        return this.horas;
    }
    
    public void setHoras(int horas) {
        this.horas = horas;
    }




}


