package Model;
// Generated 20-jul-2020 11:06:42 by Hibernate Tools 4.3.1



/**
 * Matricula generated by hbm2java
 */
public class Matricula  implements java.io.Serializable {


     private Integer idMatricula;
     private int idCurso;
     private int idAlumno;

    public Matricula() {
    }

    public Matricula(int idCurso, int idAlumno) {
       this.idCurso = idCurso;
       this.idAlumno = idAlumno;
    }
   
    public Integer getIdMatricula() {
        return this.idMatricula;
    }
    
    public void setIdMatricula(Integer idMatricula) {
        this.idMatricula = idMatricula;
    }
    public int getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }
    public int getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }




}


